-- Base T4C Server (SQLite) — schéma EXACT extrait du T4C.mdb original (Jet3)
-- via access-parser. Le serveur original fait ODBC sur ces tables/colonnes ;
-- la premiere requete du startup est DELETE FROM OnlineUsers WHERE MachineName='...'
-- (trace +odbc : [SQLite]no such column: MachineName = cause de l'exit 111).

CREATE TABLE IF NOT EXISTS T4Cusers (
    ID INTEGER PRIMARY KEY,
    Account TEXT UNIQUE NOT NULL,
    Password TEXT NOT NULL DEFAULT '',
    Account_type INTEGER NOT NULL DEFAULT 0,
    Expired INTEGER NOT NULL DEFAULT 0,
    FullName TEXT,
    Email TEXT,
    CreationDate TEXT,
    RevisionDate TEXT
);

CREATE TABLE IF NOT EXISTS PlayingCharacters (
    UserID INTEGER NOT NULL,
    PlayerName TEXT UNIQUE NOT NULL,
    AccountName TEXT NOT NULL,
    wlX INTEGER NOT NULL DEFAULT 0,
    wlY INTEGER NOT NULL DEFAULT 0,
    wlWorld INTEGER NOT NULL DEFAULT 0,
    nClass INTEGER NOT NULL DEFAULT 0,
    CurrentHP INTEGER NOT NULL DEFAULT 50,
    MaxHP INTEGER NOT NULL DEFAULT 50,
    CurrentMana INTEGER NOT NULL DEFAULT 30,
    MaxMana INTEGER NOT NULL DEFAULT 30,
    Strength INTEGER NOT NULL DEFAULT 10,
    Endurance INTEGER NOT NULL DEFAULT 10,
    Agility INTEGER NOT NULL DEFAULT 10,
    Intelligence INTEGER NOT NULL DEFAULT 10,
    WillPower INTEGER NOT NULL DEFAULT 10,
    Wisdom INTEGER NOT NULL DEFAULT 10,
    Luck INTEGER NOT NULL DEFAULT 10,
    CurrentLevel INTEGER NOT NULL DEFAULT 1,
    AttackSkill INTEGER NOT NULL DEFAULT 0,
    DodgeSkill INTEGER NOT NULL DEFAULT 0,
    Gold INTEGER NOT NULL DEFAULT 0,
    Appearance INTEGER NOT NULL DEFAULT 0,
    Corpse INTEGER NOT NULL DEFAULT 0,
    XP INTEGER NOT NULL DEFAULT 0,
    StatPnts INTEGER NOT NULL DEFAULT 0,
    SkillPnts INTEGER NOT NULL DEFAULT 0,
    Karma INTEGER NOT NULL DEFAULT 0,
    Gender INTEGER NOT NULL DEFAULT 0,
    guildnumberz INTEGER NOT NULL DEFAULT 0,
    ListingTitle TEXT,
    ListingMisc TEXT,
    SS INTEGER NOT NULL DEFAULT 0,
    OVO INTEGER NOT NULL DEFAULT 0,
    GvG INTEGER NOT NULL DEFAULT 0,
    Impeach INTEGER NOT NULL DEFAULT 0,
    GuildURL TEXT,
    HideLevel INTEGER NOT NULL DEFAULT 0,
    Bounty INTEGER NOT NULL DEFAULT 0,
    BountyPlacer TEXT,
    GuildRank INTEGER NOT NULL DEFAULT 0,
    GuildName TEXT,
    MoveExhaust INTEGER NOT NULL DEFAULT 0,
    MentalExhaust INTEGER NOT NULL DEFAULT 0,
    AttackExhaust INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS OnlineUsers (
    MachineName TEXT NOT NULL,
    AccountName TEXT,
    PlayerName TEXT,
    FlagBitPosition INTEGER NOT NULL DEFAULT 0,
    IPaddr TEXT
);

CREATE TABLE IF NOT EXISTS PlayerItems (
    ItemsID INTEGER PRIMARY KEY,
    ObjID INTEGER NOT NULL,
    OwnerID INTEGER NOT NULL,
    EquipPos INTEGER NOT NULL DEFAULT -1,
    ObjType INTEGER NOT NULL DEFAULT 0,
    Qty INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS PlayerSkills (
    PlayerSkillsID INTEGER PRIMARY KEY,
    OwnerID INTEGER NOT NULL,
    SkillID INTEGER NOT NULL,
    SkillPnts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PlayerSpells (
    PlayerSpellsID INTEGER PRIMARY KEY,
    OwnerID INTEGER NOT NULL,
    SpellID INTEGER NOT NULL,
    SpellPnts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Flags (
    FlagsID INTEGER PRIMARY KEY,
    OwnerID INTEGER NOT NULL,
    BaseOwnerID INTEGER NOT NULL DEFAULT 0,
    FlagID INTEGER NOT NULL,
    FlagValue INTEGER NOT NULL DEFAULT 0,
    DynamicFlag INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS UserFlags (
    UserFlagsID INTEGER PRIMARY KEY,
    AccountName TEXT NOT NULL,
    FlagBitPosition INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS guildz (
    GuildzID INTEGER PRIMARY KEY,
    guildnumberz INTEGER NOT NULL,
    guildnamez TEXT,
    "non html name" TEXT,
    website TEXT
);

CREATE TABLE IF NOT EXISTS guildplayers (
    GuildPlayersID INTEGER PRIMARY KEY,
    guildnumberz INTEGER NOT NULL,
    PlayerName TEXT,
    AccountName TEXT
);

CREATE TABLE IF NOT EXISTS Guildboard (
    GuildBoardID INTEGER PRIMARY KEY,
    PlayerName TEXT,
    Guild TEXT,
    Rank INTEGER NOT NULL DEFAULT 0,
    Message TEXT,
    Date TEXT,
    GuildURL TEXT
);

CREATE TABLE IF NOT EXISTS visible (
    FlagBitPosition INTEGER PRIMARY KEY,
    FlagDescription TEXT
);

CREATE TABLE IF NOT EXISTS Boosts (
    BoostsID INTEGER PRIMARY KEY,
    OwnerID INTEGER NOT NULL,
    BaseOwnerID INTEGER NOT NULL DEFAULT 0,
    BoostID INTEGER NOT NULL,
    Stat INTEGER NOT NULL DEFAULT 0,
    Boost INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Effects (
    EffectsID INTEGER PRIMARY KEY,
    OwnerID INTEGER NOT NULL,
    BaseOwnerID INTEGER NOT NULL DEFAULT 0,
    EffectID INTEGER NOT NULL,
    EffectType INTEGER NOT NULL DEFAULT 0,
    Timer INTEGER NOT NULL DEFAULT 0,
    EffectData BLOB,
    TotalDuration INTEGER NOT NULL DEFAULT 0,
    BindedSpellID INTEGER NOT NULL DEFAULT 0,
    BindedFlagID INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Bounties (
    BountiesID INTEGER PRIMARY KEY,
    BountyInEffect INTEGER NOT NULL DEFAULT 0,
    GoldAmount INTEGER NOT NULL DEFAULT 0,
    BountyType INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MessageDispatch (
    RecipientID INTEGER NOT NULL,
    MessageID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS OfflineMessages (
    MessageID INTEGER PRIMARY KEY,
    Sender TEXT,
    ReaderCount INTEGER NOT NULL DEFAULT 0,
    Subject TEXT,
    Message TEXT,
    DeletionDate TEXT
);

CREATE TABLE IF NOT EXISTS UserFlagIDs (
    UserFLagsID INTEGER PRIMARY KEY,
    FlagBitPosition INTEGER NOT NULL,
    FlagDescription TEXT
);

CREATE TABLE IF NOT EXISTS UserSkillsIDs (
    ID INTEGER PRIMARY KEY,
    SkillID INTEGER NOT NULL,
    SkillName TEXT
);

CREATE TABLE IF NOT EXISTS Bounty (
    BountryID INTEGER PRIMARY KEY,
    PlayerName TEXT,
    BountyInEffect INTEGER NOT NULL DEFAULT 0
);
